import { cpSync, mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'web');
const files = ['index.html', 'styles.css', 'app.js'];

let apiUrl = '';
if (process.env.VERCEL) {
  apiUrl = '';
} else if (existsSync(join(root, 'config.local.js'))) {
  const raw = readFileSync(join(root, 'config.local.js'), 'utf8');
  const m = raw.match(/FITNESS_API\s*=\s*['"]([^'"]*)['"]/);
  if (m) apiUrl = m[1];
}

const configJs = `// Auto-generated by scripts/sync-www.mjs\nwindow.FITNESS_API = '${apiUrl}';\n`;

const dest = join(root, 'public');
mkdirSync(dest, { recursive: true });
for (const file of files) {
  cpSync(join(src, file), join(dest, file));
}
writeFileSync(join(dest, 'config.js'), configJs);

console.log('Synced public/ from web/');
console.log('API base:', apiUrl || '(same-origin)');
